version: '3.0'

services:
  conrad:
    container_name: conrad
    build: Conrad
    volumes:
      - ./Conrad/config/:/app/config/:delegated
    ports:
      - 127.0.0.1:4000:4000
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    container_name: ollama
    build:
      context: .
      dockerfile_inline: |
        FROM ollama/ollama
        RUN apt-get install curl -y
    volumes:
      - ./ollama_models:/root/.ollama
    ports:
      - 11434:11434
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:11434 || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 3
